#Получение токена по username & password.
#Логин и пороль можно получить: python manage.py createsuperuser
#Затем поменять Token в http запросах. Токен - POST запрос ниже.
POST http://127.0.0.1:8000/api-token-auth/
Content-Type: application/json

{
    "username": "ee-2@ya.ru",
    "password": "Vitaliya"
}
### -------------------trip--------------------------
# Дерево запросов.
GET  http://127.0.0.1:8000/api/v1/trip/12
Content-Type: application/json
Authorization: Token bbe8f7f7b688272b1bba73210b69a8dcf070d0a6
###
GET  http://127.0.0.1:8000/api/v1/trip/
Content-Type: application/json
Authorization: Token bbe8f7f7b688272b1bba73210b69a8dcf070d0a6
###
# Даты должны быть больше текущих.
POST http://127.0.0.1:8000/api/v1/trip/
Content-Type: application/json
Authorization: Token bbe8f7f7b688272b1bba73210b69a8dcf070d0a6

{
    "time_out": "2022-07-23T05:30:00Z",
    "time_in": "2022-07-23T06:00:00Z",
    "company": "1",
    "plane": "1",
    "airport_from": "1",
    "airport_to": "2"
}
###
# Слаг ID взять из предыдущего ответа на POST запрос.
# Даты должны быть больше текущих.
PUT http://127.0.0.1:8000/api/v1/trip/19/
Content-Type: application/json
Authorization: Token bbe8f7f7b688272b1bba73210b69a8dcf070d0a6

{
    "time_out": "2022-07-23T05:30:00Z",
    "time_in": "2022-07-23T07:00:00Z",
    "company": "1",
    "plane": "1",
    "airport_from": "1",
    "airport_to": "2"
}
###
# Слаг ID взять из предыдущего ответа на POST запрос
DELETE http://127.0.0.1:8000/api/v1/trip/19/
Content-Type: application/json
Authorization: Token bbe8f7f7b688272b1bba73210b69a8dcf070d0a6
###
GET  http://127.0.0.1:8000/api/v1/trip?airport_from=2&airport_to=1
Content-Type: application/json
Authorization: Token bbe8f7f7b688272b1bba73210b69a8dcf070d0a6
###
GET  http://127.0.0.1:8000/api/v1/trip?company=1&airport_from=1
Content-Type: application/json
Authorization: Token bbe8f7f7b688272b1bba73210b69a8dcf070d0a6
###
GET  http://127.0.0.1:8000/api/v1/trip?search=Пулково-1
Content-Type: application/json
Authorization: Token bbe8f7f7b688272b1bba73210b69a8dcf070d0a6

### -------------------pass_in_trip--------------
GET  http://127.0.0.1:8000/api/v1/pass_in_trip/
Content-Type: application/json
Authorization: Token bbe8f7f7b688272b1bba73210b69a8dcf070d0a6
###
GET  http://127.0.0.1:8000/api/v1/pass_in_trip/1/
Content-Type: application/json
Authorization: Token bbe8f7f7b688272b1bba73210b69a8dcf070d0a6
###
POST http://127.0.0.1:8000/api/v1/pass_in_trip/
Content-Type: application/json
Authorization: Token bbe8f7f7b688272b1bba73210b69a8dcf070d0a6

{
    "place": "99",
    "passenger": "1",
    "trip": "1"
}
###
# Слаг ID взять из предыдущего ответа на POST запрос
PUT http://127.0.0.1:8000/api/v1/pass_in_trip/20/
Content-Type: application/json
Authorization: Token bbe8f7f7b688272b1bba73210b69a8dcf070d0a6

{
    "place": "97",
    "passenger": "1",
    "trip": "1"
}
###
# Слаг ID взять из предыдущего ответа на POST запрос
DELETE http://127.0.0.1:8000/api/v1/pass_in_trip/20/
Content-Type: application/json
Authorization: Token bbe8f7f7b688272b1bba73210b69a8dcf070d0a6
###
GET  http://127.0.0.1:8000/api/v1/pass_in_trip/?passenger=1
Content-Type: application/json
Authorization: Token bbe8f7f7b688272b1bba73210b69a8dcf070d0a6
###
GET  http://127.0.0.1:8000/api/v1/pass_in_trip/?search=pir
Content-Type: application/json
Authorization: Token bbe8f7f7b688272b1bba73210b69a8dcf070d0a6

###  -------------------airport--------------------
GET  http://127.0.0.1:8000/api/v1/airport/
Content-Type: application/json
Authorization: Token bbe8f7f7b688272b1bba73210b69a8dcf070d0a6
###
GET  http://127.0.0.1:8000/api/v1/airport/1/
Content-Type: application/json
Authorization: Token bbe8f7f7b688272b1bba73210b69a8dcf070d0a6
###
POST http://127.0.0.1:8000/api/v1/airport/
Content-Type: application/json
Authorization: Token bbe8f7f7b688272b1bba73210b69a8dcf070d0a6

{
    "name": "test_Airport"
}
###
# Слаг ID взять из предыдущего ответа на POST запрос
PUT http://127.0.0.1:8000/api/v1/airport/7/
Content-Type: application/json
Authorization: Token bbe8f7f7b688272b1bba73210b69a8dcf070d0a6

{
    "name": "test_Airport_2"
}
###
DELETE http://127.0.0.1:8000/api/v1/airport/7/
Content-Type: application/json
Authorization: Token bbe8f7f7b688272b1bba73210b69a8dcf070d0a6

### -------------company----------------
GET  http://127.0.0.1:8000/api/v1/company/
Content-Type: application/json
Authorization: Token bbe8f7f7b688272b1bba73210b69a8dcf070d0a6
###
GET  http://127.0.0.1:8000/api/v1/company/1/
Content-Type: application/json
Authorization: Token bbe8f7f7b688272b1bba73210b69a8dcf070d0a6
###
POST http://127.0.0.1:8000/api/v1/company/
Content-Type: application/json
Authorization: Token bbe8f7f7b688272b1bba73210b69a8dcf070d0a6

{
    "name": "UralAir"
}
###
# Слаг ID взять из предыдущего ответа на POST запрос
PUT http://127.0.0.1:8000/api/v1/company/4/
Content-Type: application/json
Authorization: Token bbe8f7f7b688272b1bba73210b69a8dcf070d0a6

{
    "name": "UralAir_2"
}
###
DELETE http://127.0.0.1:8000/api/v1/company/4/
Content-Type: application/json
Authorization: Token bbe8f7f7b688272b1bba73210b69a8dcf070d0a6

### ---------------plane--------------------
GET  http://127.0.0.1:8000/api/v1/plane/
Content-Type: application/json
Authorization: Token bbe8f7f7b688272b1bba73210b69a8dcf070d0a6
###
GET  http://127.0.0.1:8000/api/v1/plane/1/
Content-Type: application/json
Authorization: Token bbe8f7f7b688272b1bba73210b69a8dcf070d0a6
###
POST http://127.0.0.1:8000/api/v1/plane/
Content-Type: application/json
Authorization: Token bbe8f7f7b688272b1bba73210b69a8dcf070d0a6

{
    "name": "TU-144",
    "number": "78787878",
    "capacity": "152"
}
###
PUT http://127.0.0.1:8000/api/v1/plane/2/
Content-Type: application/json
Authorization: Token bbe8f7f7b688272b1bba73210b69a8dcf070d0a6

{
    "name": "TU-144",
    "number": "99999999",
    "capacity": "155"
}
###
DELETE http://127.0.0.1:8000/api/v1/plane/2/
Content-Type: application/json
Authorization: Token bbe8f7f7b688272b1bba73210b69a8dcf070d0a6