# Generated by Django 2.2.19 on 2022-06-22 14:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import trip.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название аэропорта', max_length=128, unique=True, verbose_name='Название аэропорта')),
            ],
            options={
                'verbose_name': 'Аэропорт',
                'verbose_name_plural': 'Аэропорты',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название компании', max_length=64, unique=True, verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название самолета', max_length=128, unique=True, verbose_name='Название самолета')),
                ('number', models.IntegerField(help_text='Введите номер самолета', verbose_name='Номер самолета')),
                ('ready', models.BooleanField(default=False, help_text='Измените готовность самолета', verbose_name='Готовность самолета')),
                ('capacity', models.SmallIntegerField(help_text='Введите кол-во мест в самолете', verbose_name='Количество мест')),
            ],
            options={
                'verbose_name': 'Самолет',
                'verbose_name_plural': 'Самолеты',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_out', models.DateTimeField(validators=[trip.validators.validator_datetime], verbose_name='Дата/Время вылета')),
                ('time_in', models.DateTimeField(validators=[trip.validators.validator_datetime], verbose_name='Дата/Время прилета')),
                ('airport_from', models.ForeignKey(help_text='Из аэропорта', on_delete=django.db.models.deletion.CASCADE, related_name='trips_from', to='trip.Airport', verbose_name='Из аэропорта')),
                ('airport_to', models.ForeignKey(help_text='В аэропорт', on_delete=django.db.models.deletion.CASCADE, related_name='trips_to', to='trip.Airport', verbose_name='В аэропорт')),
                ('company', models.ForeignKey(help_text='Компания', on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trip.Company', verbose_name='Компания')),
                ('plane', models.ForeignKey(help_text='Самолет', on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trip.Plane', verbose_name='Самолет')),
            ],
            options={
                'verbose_name': 'Перелет',
                'verbose_name_plural': 'Перелеты',
            },
        ),
        migrations.CreateModel(
            name='Pass_in_trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.SmallIntegerField(help_text='Введите номер места', unique=True, validators=[django.core.validators.MinValueValidator(1, 'Место не может быть менее 1.'), django.core.validators.MaxValueValidator(300, 'Место не может быть больше, чем мест в самолете.')], verbose_name='Номер места')),
                ('passenger', models.ForeignKey(help_text='Пассажир', on_delete=django.db.models.deletion.CASCADE, related_name='pass_in_trip', to=settings.AUTH_USER_MODEL, verbose_name='Пассажир')),
                ('trip', models.ForeignKey(help_text='Пассажиры в рейсе', on_delete=django.db.models.deletion.CASCADE, related_name='pass_in_trips', to='trip.Trip', verbose_name='Пассажиры в рейсе')),
            ],
            options={
                'verbose_name': 'Пассажир_место',
                'verbose_name_plural': 'Пассажиры_места',
            },
        ),
    ]
