# Generated by Django 2.2.19 on 2022-06-22 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass_in_trip',
            name='place',
            field=models.SmallIntegerField(help_text='Введите номер места', unique=True, validators=[django.core.validators.MinValueValidator(1, 'Место не может быть менее 1.')], verbose_name='Номер места'),
        ),
    ]
