# Generated by Django 4.0.5 on 2022-06-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_alter_pass_in_trip_place_alter_plane_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='ap_time_zone',
            field=models.CharField(choices=[(0, 'UTC'), (3, 'Europe/Moscow')], default='UTC', help_text='Введите таймзону аэропорта', max_length=128, verbose_name='Таймзона аэропорта'),
        ),
    ]
