# Generated by Django 4.0.5 on 2022-06-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_alter_airport_ap_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='ap_time_zone',
            field=models.CharField(choices=[('UTC', 'UTC'), ('Moscow', 'Europe/Moscow'), ('Kamchatka', 'Asia/Kamchatka')], default='UTC', help_text='Введите таймзону аэропорта', max_length=128, verbose_name='Таймзона аэропорта'),
        ),
    ]
