name: Avia_trip workflow

on: [push]

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  DB_ENGINE: ${{ secrets.DB_ENGINE }}
  DB_NAME: ${{ secrets.DB_NAME }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}

jobs:
  django-unittest:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r avia/requirements.txt
    - name: Run migrations
      run: python avia/manage.py migrate
    - name: Run tests
      run: python avia/manage.py test api