name: Django-app workflow

on: [push]

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip 
        pip install -r avia/requirements.txt 

    - name: Test with django tests
      run: |
        python avia/manage.py test

